package hermes.client.view.frame;

import com.hermes.components.HMFrames.HMInternalFrame;
import com.hermes.components.HMFrames.HMPanel;
import com.hermes.components.utils.ImageFactory;
import hermes.client.controll.frame.DesktopController;
import hermes.client.view.register.RegisterBugReport;
import hermes.client.view.toolbar.Novo;
import hermes.client.view.toolbar.Pesquisa;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.DesktopPaneUI;

/**
 *
 * @author iury
 */
public class Desktop extends javax.swing.JFrame {

    private String username;
    private DesktopController controller;

    public Desktop() {
        controller = new DesktopController();
        initComponents();
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(tela.width - 100, tela.height - 200);
        setExtendedState(MAXIMIZED_BOTH);
        desktop_pane.setUI(new DesktopPaneUI() {
            @Override
            public void installUI(JComponent c) {
                // TODO Auto-generated method stub
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                } catch (Exception e) {
                    e.printStackTrace();
                }
                super.installUI(c);
            }
        });
        setIconImage(new ImageFactory().getIcon("hermes_icon.png", 600, 600).getImage());
        controller.startSystemHour(tf_system_hour);
    }

    public void setUsername(String username) {
        this.username = username;
        controller.showUsername(tf_user, username);
    }

    public String getUsername() {
        return this.username;
    }

    public void addInternalFrame(HMInternalFrame frame) {
        final HMInternalFrame finalFrame = frame;
        new Thread() {
            @Override
            public void run() {
                finalFrame.setVisible(true);
                finalFrame.setResizable(false);
                finalFrame.setClosable(true);
                setCenterPosition(finalFrame);
                desktop_pane.add(finalFrame);
                finalFrame.toFront();
            }
        }.start();
    }

    public HMInternalFrame getSelectedFrame() {
        return (HMInternalFrame) desktop_pane.getSelectedFrame();
    }

    public void setCenterPosition(HMInternalFrame frame) {
        Dimension d = this.getSize();
        frame.setLocation((d.width - frame.getWidth()) / 2, (d.height - frame.getHeight()) / 3);
    }

    public void novo() {
        addInternalFrame(new Novo());
    }

    public void salva() {
        try {
            HMInternalFrame frame = getSelectedFrame();
            HMPanel panel = frame.getHMPanel();
            panel.salvar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione uma tela a ser salva!");
        }

    }

    public void pesquisa() {
        addInternalFrame(new Pesquisa());
    }

    public void bugReport() {
        addInternalFrame(new RegisterBugReport());
    }

    public void exitVerification() {
        int verif = JOptionPane.showConfirmDialog(this, "Você tem certeza que quer fechar esta aplicação?", "Verificação", JOptionPane.YES_NO_OPTION);
        if (verif == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop_pane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        tf_user = new javax.swing.JLabel();
        tf_system_hour = new javax.swing.JLabel();
        toolbar = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPropriedades = new javax.swing.JButton();
        btnPropriedades1 = new javax.swing.JButton();
        menu_bar = new javax.swing.JMenuBar();
        menu_cadastros = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Hermes");
        setBackground(new java.awt.Color(235, 251, 253));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktop_pane.setBackground(new java.awt.Color(235, 251, 253));

        jPanel1.setBackground(new java.awt.Color(224, 237, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 102, 255), null));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(126, 30));

        tf_system_hour.setText("Hora do sistema:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_system_hour, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tf_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_system_hour, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        toolbar.setBackground(new java.awt.Color(224, 237, 255));
        toolbar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 102, 255), null));
        toolbar.setFloatable(false);
        toolbar.setForeground(new java.awt.Color(204, 255, 255));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);

        btnNovo.setBackground(new java.awt.Color(0, 102, 255));
        btnNovo.setForeground(new java.awt.Color(51, 153, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_add.png"))); // NOI18N
        btnNovo.setBorderPainted(false);
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setIconTextGap(0);
        btnNovo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNovo.setMaximumSize(new java.awt.Dimension(80, 71));
        btnNovo.setMinimumSize(new java.awt.Dimension(80, 71));
        btnNovo.setOpaque(false);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        toolbar.add(btnNovo);

        btnAbrir.setForeground(new java.awt.Color(51, 153, 255));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open_folder.png"))); // NOI18N
        btnAbrir.setBorderPainted(false);
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAbrir.setMaximumSize(new java.awt.Dimension(80, 71));
        btnAbrir.setMinimumSize(new java.awt.Dimension(80, 71));
        btnAbrir.setOpaque(false);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnAbrir);

        btnExcluir.setForeground(new java.awt.Color(51, 153, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_1.png"))); // NOI18N
        btnExcluir.setBorderPainted(false);
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setIconTextGap(0);
        btnExcluir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnExcluir.setMaximumSize(new java.awt.Dimension(80, 71));
        btnExcluir.setMinimumSize(new java.awt.Dimension(71, 71));
        btnExcluir.setOpaque(false);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnExcluir);

        btnSalvar.setForeground(new java.awt.Color(51, 153, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png"))); // NOI18N
        btnSalvar.setBorderPainted(false);
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setMaximumSize(new java.awt.Dimension(80, 71));
        btnSalvar.setMinimumSize(new java.awt.Dimension(80, 71));
        btnSalvar.setOpaque(false);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        toolbar.add(btnSalvar);

        btnPesquisar.setForeground(new java.awt.Color(51, 153, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        btnPesquisar.setBorderPainted(false);
        btnPesquisar.setFocusable(false);
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisar.setMaximumSize(new java.awt.Dimension(80, 71));
        btnPesquisar.setMinimumSize(new java.awt.Dimension(80, 71));
        btnPesquisar.setOpaque(false);
        btnPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        toolbar.add(btnPesquisar);

        btnImprimir.setForeground(new java.awt.Color(51, 153, 255));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        btnImprimir.setBorderPainted(false);
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setMaximumSize(new java.awt.Dimension(80, 71));
        btnImprimir.setMinimumSize(new java.awt.Dimension(80, 71));
        btnImprimir.setOpaque(false);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnImprimir);

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setMaximumSize(new java.awt.Dimension(3, 70));
        jSeparator1.setMinimumSize(new java.awt.Dimension(3, 70));
        jSeparator1.setName(""); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(3, 70));
        toolbar.add(jSeparator1);

        btnPropriedades.setForeground(new java.awt.Color(51, 153, 255));
        btnPropriedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear.png"))); // NOI18N
        btnPropriedades.setBorderPainted(false);
        btnPropriedades.setFocusable(false);
        btnPropriedades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPropriedades.setMaximumSize(new java.awt.Dimension(80, 71));
        btnPropriedades.setMinimumSize(new java.awt.Dimension(80, 71));
        btnPropriedades.setOpaque(false);
        btnPropriedades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnPropriedades);

        btnPropriedades1.setForeground(new java.awt.Color(51, 153, 255));
        btnPropriedades1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        btnPropriedades1.setBorderPainted(false);
        btnPropriedades1.setFocusable(false);
        btnPropriedades1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPropriedades1.setMaximumSize(new java.awt.Dimension(80, 71));
        btnPropriedades1.setMinimumSize(new java.awt.Dimension(80, 71));
        btnPropriedades1.setOpaque(false);
        btnPropriedades1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPropriedades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropriedades1ActionPerformed(evt);
            }
        });
        toolbar.add(btnPropriedades1);

        menu_bar.setBackground(new java.awt.Color(235, 251, 253));
        menu_bar.setOpaque(false);

        menu_cadastros.setText("Cadastros");
        menu_bar.add(menu_cadastros);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop_pane)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1419, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        novo();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisa();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salva();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exitVerification();
    }//GEN-LAST:event_formWindowClosing

    private void btnPropriedades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropriedades1ActionPerformed
        bugReport();
    }//GEN-LAST:event_btnPropriedades1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                break;
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPropriedades;
    private javax.swing.JButton btnPropriedades1;
    private javax.swing.JButton btnSalvar;
    public static javax.swing.JDesktopPane desktop_pane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JMenu menu_cadastros;
    private javax.swing.JLabel tf_system_hour;
    private javax.swing.JLabel tf_user;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
