package hermes.client.view.frame;

import com.hermes.components.utils.ImageFactory;
import hermes.client.controll.frame.LoginController;
import hermes.client.main.Main;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.japura.modal.Modal;

/**
 *
 * @author iury
 */
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        initComponent();
        setIconImage(new ImageFactory().getIcon("hermes_icon.png", 600, 600).getImage());
        setAutoRequestFocus(true);
    }

    public void initComponent() {
        setLocationRelativeTo(null);
        tf_usuario.setStaticIcon("admin.png", 18, 18);
        btn_login.setEnabled(false);
    }

    public void analizeFields() {
        if (tf_senha.isValid() && tf_usuario.isValid()) {
            btn_login.setEnabled(true);
        } else {
            btn_login.setEnabled(false);
        }
    }

    public void login() {
        String usuario = tf_usuario.getText();
        String senha = String.valueOf(tf_senha.getText());
        LoginController lc = new LoginController();
        if (lc.login(usuario, senha)) {
            Modal.closeAllModals(Main.desktop);
            Modal.closeAllModals(Main.login);
            Main.desktop.setUsername(usuario);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário e/ou senha incorretos, tente novamente!");
        }
    }

    public void exitVerification() {
        int verif = JOptionPane.showConfirmDialog(this, "Você tem certeza que quer fechar esta aplicação?", "Verificação", JOptionPane.YES_NO_OPTION);
        if (verif == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_mae = new javax.swing.JPanel();
        lb_img = new javax.swing.JLabel();
        painel_login = new javax.swing.JPanel();
        tf_usuario = new com.hermes.components.HMFields.HMTextField();
        lb_usuario = new javax.swing.JLabel();
        lb_senha = new javax.swing.JLabel();
        tf_senha = new com.hermes.components.HMFields.HMPasswordField();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        painel_mae.setBackground(new java.awt.Color(255, 255, 255));
        painel_mae.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));

        lb_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N

        painel_login.setOpaque(false);

        tf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuarioActionPerformed(evt);
            }
        });
        tf_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_usuarioFocusLost(evt);
            }
        });
        tf_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_usuarioKeyReleased(evt);
            }
        });

        lb_usuario.setText("Usuário:");

        lb_senha.setText("Senha:");

        tf_senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_senhaFocusLost(evt);
            }
        });
        tf_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_senhaKeyReleased(evt);
            }
        });

        btn_login.setText("Entrar");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_loginLayout = new javax.swing.GroupLayout(painel_login);
        painel_login.setLayout(painel_loginLayout);
        painel_loginLayout.setHorizontalGroup(
            painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_loginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_senha)
                    .addComponent(lb_usuario))
                .addGap(18, 18, 18)
                .addGroup(painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(tf_senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painel_loginLayout.setVerticalGroup(
            painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_loginLayout.createSequentialGroup()
                        .addGroup(painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_usuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_senha)
                            .addComponent(tf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painel_maeLayout = new javax.swing.GroupLayout(painel_mae);
        painel_mae.setLayout(painel_maeLayout);
        painel_maeLayout.setHorizontalGroup(
            painel_maeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_maeLayout.createSequentialGroup()
                .addComponent(lb_img)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(painel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painel_maeLayout.setVerticalGroup(
            painel_maeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_maeLayout.createSequentialGroup()
                .addComponent(lb_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_mae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_mae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        login();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void tf_usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_usuarioFocusLost
        analizeFields();
    }//GEN-LAST:event_tf_usuarioFocusLost

    private void tf_senhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_senhaFocusLost
        analizeFields();
    }//GEN-LAST:event_tf_senhaFocusLost

    private void tf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuarioActionPerformed
        analizeFields();
    }//GEN-LAST:event_tf_usuarioActionPerformed

    private void tf_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_usuarioKeyReleased
        analizeFields();
    }//GEN-LAST:event_tf_usuarioKeyReleased

    private void tf_senhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_senhaKeyReleased
        analizeFields();
    }//GEN-LAST:event_tf_senhaKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exitVerification();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel lb_img;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPanel painel_login;
    private javax.swing.JPanel painel_mae;
    private com.hermes.components.HMFields.HMPasswordField tf_senha;
    private com.hermes.components.HMFields.HMTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
