package hermes.client.view.register;

import com.hermes.components.HMFrames.HMPanel;
import com.hermes.components.utils.ImageFactory;
import hermes.client.controll.tipoProduto.TipoProdutoController;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author iury
 */
public class RegisterProdutoFabricado extends HMPanel {

    public void initFields() {
        //TEXT FIELDS
        tf_nome.setObrigatory(true);
        //COMBO BOXES
        cb_tipo.setValues(new TipoProdutoController().getTipos());
        //BUTTONS
        btn_escolher.setIcon(new ImageFactory().getIcon("open_folder_add.png", 25, 25));
    }

    public void abrirFileChooser() {
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                ImageIcon i = new ImageIcon(file.getAbsolutePath());
                i.setImage(i.getImage().getScaledInstance(lb_foto.getWidth(), lb_foto.getHeight(), 100));
                lb_foto.setIcon(i);
            } catch (Exception ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }

    public RegisterProdutoFabricado() {
        initComponents();
        initFields();
        setSize(625, 337);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        pn_cadastro = new javax.swing.JPanel();
        pn_identificacao = new javax.swing.JPanel();
        ln_nome = new javax.swing.JLabel();
        tf_nome = new com.hermes.components.HMFields.HMTextField();
        lb_tipo = new javax.swing.JLabel();
        cb_tipo = new com.hermes.components.HMSelections.HMComboBox();
        pn_foto = new javax.swing.JPanel();
        btn_escolher = new javax.swing.JButton();
        lb_foto = new javax.swing.JLabel();
        pn_descricao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp_descricao = new javax.swing.JTextPane();
        pn_valores = new javax.swing.JPanel();
        lb_custo = new javax.swing.JLabel();
        lb_valor_venda = new javax.swing.JLabel();
        lb_qtdade = new javax.swing.JLabel();
        tf_custo = new com.hermes.components.HMFields.HMMonetaryField();
        tf_valor_venda = new com.hermes.components.HMFields.HMMonetaryField();
        spn_qtdade = new javax.swing.JSpinner();

        setOpaque(false);

        pn_cadastro.setOpaque(false);

        pn_identificacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Identificação"));
        pn_identificacao.setOpaque(false);

        ln_nome.setText("Nome:");

        lb_tipo.setText("Tipo:");

        javax.swing.GroupLayout pn_identificacaoLayout = new javax.swing.GroupLayout(pn_identificacao);
        pn_identificacao.setLayout(pn_identificacaoLayout);
        pn_identificacaoLayout.setHorizontalGroup(
            pn_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_identificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_tipo)
                    .addComponent(ln_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        pn_identificacaoLayout.setVerticalGroup(
            pn_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_identificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ln_nome)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_identificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tipo)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_foto.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));
        pn_foto.setOpaque(false);

        btn_escolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escolherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_fotoLayout = new javax.swing.GroupLayout(pn_foto);
        pn_foto.setLayout(pn_fotoLayout);
        pn_fotoLayout.setHorizontalGroup(
            pn_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_fotoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_escolher, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pn_fotoLayout.setVerticalGroup(
            pn_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_fotoLayout.createSequentialGroup()
                .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_escolher, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn_descricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        pn_descricao.setEnabled(false);
        pn_descricao.setOpaque(false);

        jScrollPane1.setViewportView(tp_descricao);

        javax.swing.GroupLayout pn_descricaoLayout = new javax.swing.GroupLayout(pn_descricao);
        pn_descricao.setLayout(pn_descricaoLayout);
        pn_descricaoLayout.setHorizontalGroup(
            pn_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_descricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pn_descricaoLayout.setVerticalGroup(
            pn_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_descricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_valores.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));
        pn_valores.setOpaque(false);

        lb_custo.setText("Custo:");

        lb_valor_venda.setText("Valor Venda:");

        lb_qtdade.setText("Quantidade:");

        javax.swing.GroupLayout pn_valoresLayout = new javax.swing.GroupLayout(pn_valores);
        pn_valores.setLayout(pn_valoresLayout);
        pn_valoresLayout.setHorizontalGroup(
            pn_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_valoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_custo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_valor_venda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_qtdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn_qtdade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_valoresLayout.setVerticalGroup(
            pn_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_valoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_custo)
                        .addComponent(lb_valor_venda)
                        .addComponent(lb_qtdade)
                        .addComponent(tf_custo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_valor_venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(spn_qtdade))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_cadastroLayout = new javax.swing.GroupLayout(pn_cadastro);
        pn_cadastro.setLayout(pn_cadastroLayout);
        pn_cadastroLayout.setHorizontalGroup(
            pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_valores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_cadastroLayout.createSequentialGroup()
                        .addComponent(pn_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pn_identificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_cadastroLayout.setVerticalGroup(
            pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_cadastroLayout.createSequentialGroup()
                        .addComponent(pn_identificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(131, 131, 131))
                    .addGroup(pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pn_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_valores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_escolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escolherActionPerformed
        abrirFileChooser();
    }//GEN-LAST:event_btn_escolherActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_escolher;
    private com.hermes.components.HMSelections.HMComboBox cb_tipo;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_custo;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lb_qtdade;
    private javax.swing.JLabel lb_tipo;
    private javax.swing.JLabel lb_valor_venda;
    private javax.swing.JLabel ln_nome;
    private javax.swing.JPanel pn_cadastro;
    private javax.swing.JPanel pn_descricao;
    private javax.swing.JPanel pn_foto;
    private javax.swing.JPanel pn_identificacao;
    private javax.swing.JPanel pn_valores;
    private javax.swing.JSpinner spn_qtdade;
    private com.hermes.components.HMFields.HMMonetaryField tf_custo;
    private com.hermes.components.HMFields.HMTextField tf_nome;
    private com.hermes.components.HMFields.HMMonetaryField tf_valor_venda;
    private javax.swing.JTextPane tp_descricao;
    // End of variables declaration//GEN-END:variables
}
