package hermes.client.view.register;

import com.hermes.components.HMFrames.HMPanel;

/**
 *
 * @author iury
 */
public class RegisterTipoProduto extends HMPanel {

    public void initFields() {
        tf_nome.setObrigatory(true);
        tf_abrev.setObrigatory(true);
        tf_abrev.setSpecial(true);
    }

    public RegisterTipoProduto() {
        initComponents();
        initFields();
        setSize(332, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_cad_tipo_produto = new javax.swing.JPanel();
        pn_informacoes = new javax.swing.JPanel();
        lb_nome = new javax.swing.JLabel();
        tf_nome = new com.hermes.components.HMFields.HMTextField();
        lb_abrev = new javax.swing.JLabel();
        tf_abrev = new com.hermes.components.HMFields.HMTextField();
        pn_descricao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp_descricao = new javax.swing.JTextPane();

        setOpaque(false);

        pn_cad_tipo_produto.setOpaque(false);

        pn_informacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));
        pn_informacoes.setOpaque(false);

        lb_nome.setText("Nome:");

        lb_abrev.setText("Abreviação:");

        javax.swing.GroupLayout pn_informacoesLayout = new javax.swing.GroupLayout(pn_informacoes);
        pn_informacoes.setLayout(pn_informacoesLayout);
        pn_informacoesLayout.setHorizontalGroup(
            pn_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_informacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_nome)
                    .addComponent(lb_abrev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(tf_abrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_informacoesLayout.setVerticalGroup(
            pn_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_informacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nome)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_abrev)
                    .addComponent(tf_abrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_descricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        pn_descricao.setOpaque(false);

        jScrollPane1.setViewportView(tp_descricao);

        javax.swing.GroupLayout pn_descricaoLayout = new javax.swing.GroupLayout(pn_descricao);
        pn_descricao.setLayout(pn_descricaoLayout);
        pn_descricaoLayout.setHorizontalGroup(
            pn_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_descricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pn_descricaoLayout.setVerticalGroup(
            pn_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_descricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pn_cad_tipo_produtoLayout = new javax.swing.GroupLayout(pn_cad_tipo_produto);
        pn_cad_tipo_produto.setLayout(pn_cad_tipo_produtoLayout);
        pn_cad_tipo_produtoLayout.setHorizontalGroup(
            pn_cad_tipo_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_cad_tipo_produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_cad_tipo_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pn_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_informacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_cad_tipo_produtoLayout.setVerticalGroup(
            pn_cad_tipo_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cad_tipo_produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_cad_tipo_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_cad_tipo_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_abrev;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JPanel pn_cad_tipo_produto;
    private javax.swing.JPanel pn_descricao;
    private javax.swing.JPanel pn_informacoes;
    private com.hermes.components.HMFields.HMTextField tf_abrev;
    private com.hermes.components.HMFields.HMTextField tf_nome;
    private javax.swing.JTextPane tp_descricao;
    // End of variables declaration//GEN-END:variables
}
