package hermes.client.view.register;

import com.hermes.components.HMFields.HMFormattedTextField;
import com.hermes.components.HMFrames.HMPanel;
import com.hermes.components.utils.ImageFactory;
import hermes.client.controller.utils.EstadosController;
import hermes.ejb.entidades.Estados;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author iury
 */
public class RegisterVendedor extends HMPanel {

    public void initFields() {
        //TEXT FIELDS
        tf_celular.setMask(HMFormattedTextField.TELEFONE);
        tf_cep.setObrigatory(true);
        tf_cep.setMask(HMFormattedTextField.CEP);
        tf_cpf.setObrigatory(true);
        tf_cpf.setMask(HMFormattedTextField.CPF);
        tf_data_nasc.setMask(HMFormattedTextField.DATA);
        tf_data_nasc.setObrigatory(true);
        tf_endereco.setObrigatory(true);
        tf_nome.setObrigatory(true);
        tf_telefone.setObrigatory(true);
        tf_telefone.setMask(HMFormattedTextField.TELEFONE);
        tf_usuario.setObrigatory(true);
        tf_usuario.setSpecial(true);
        //COMBO BOXES
        String sexo[] = {"Masculino", "Feminino"};
        cb_sexo.setValues(sexo);
        cb_estado.setValues(new EstadosController().getEstados());
        verificaEstado();
        //BUTTONS
        btn_escolher.setIcon(new ImageFactory().getIcon("open_folder_add.png", 25, 25));
    }

    public void verificaEstado() {
        cb_cidade.removeAllItems();
        cb_cidade.setValues(new EstadosController().getCidadesByEstado(((Estados) cb_estado.getSelectedItem())));
    }

    public void abrirFileChooser() {
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                ImageIcon i = new ImageIcon(file.getAbsolutePath());
                i.setImage(i.getImage().getScaledInstance(lb_foto.getWidth(), lb_foto.getHeight(), 100));
                lb_foto.setIcon(i);
            } catch (Exception ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }

    public RegisterVendedor() {
        initComponents();
        setSize(680, 477);
        initFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        pn_cad_vendedor = new javax.swing.JPanel();
        lb_login = new javax.swing.JPanel();
        lb_usuario = new javax.swing.JLabel();
        lb_senha = new javax.swing.JLabel();
        lb_repete_senha = new javax.swing.JLabel();
        lb_carga_horaria = new javax.swing.JLabel();
        tf_usuario = new com.hermes.components.HMFields.HMTextField();
        tf_senha = new com.hermes.components.HMFields.HMPasswordField();
        tf_repete_senha = new com.hermes.components.HMFields.HMPasswordField();
        spn_carga_horaria = new javax.swing.JSpinner();
        pn_contato = new javax.swing.JPanel();
        lb_telefone = new javax.swing.JLabel();
        lb_celular = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        tf_telefone = new com.hermes.components.HMFields.HMFormattedTextField();
        tf_celular = new com.hermes.components.HMFields.HMFormattedTextField();
        tf_email = new com.hermes.components.HMFields.HMTextField();
        pn_dados_pessoais = new javax.swing.JPanel();
        lb_nome = new javax.swing.JLabel();
        lb_sexo = new javax.swing.JLabel();
        lb_cpf = new javax.swing.JLabel();
        lb_data_nasc = new javax.swing.JLabel();
        tf_nome = new com.hermes.components.HMFields.HMTextField();
        tf_cpf = new com.hermes.components.HMFields.HMFormattedTextField();
        cb_sexo = new com.hermes.components.HMSelections.HMComboBox();
        tf_data_nasc = new com.hermes.components.HMFields.HMFormattedTextField();
        pn_foto = new javax.swing.JPanel();
        btn_escolher = new javax.swing.JButton();
        lb_foto = new javax.swing.JLabel();
        pn_localizacao = new javax.swing.JPanel();
        lb_estado = new javax.swing.JLabel();
        lb_cidade = new javax.swing.JLabel();
        lb_endereco = new javax.swing.JLabel();
        lb_numero = new javax.swing.JLabel();
        lb_cep = new javax.swing.JLabel();
        lb_descricao = new javax.swing.JLabel();
        cb_estado = new com.hermes.components.HMSelections.HMComboBox();
        cb_cidade = new com.hermes.components.HMSelections.HMComboBox();
        tf_numero = new com.hermes.components.HMFields.HMTextField();
        tf_endereco = new com.hermes.components.HMFields.HMTextField();
        tf_desc_end = new com.hermes.components.HMFields.HMTextField();
        tf_cep = new com.hermes.components.HMFields.HMFormattedTextField();

        setOpaque(false);

        pn_cad_vendedor.setOpaque(false);

        lb_login.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        lb_login.setOpaque(false);

        lb_usuario.setText("Usuário:");

        lb_senha.setText("Senha:");

        lb_repete_senha.setText("Repete Senha:");

        lb_carga_horaria.setText("Carga Horária:");

        javax.swing.GroupLayout lb_loginLayout = new javax.swing.GroupLayout(lb_login);
        lb_login.setLayout(lb_loginLayout);
        lb_loginLayout.setHorizontalGroup(
            lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb_loginLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_usuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_senha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tf_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lb_loginLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lb_carga_horaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lb_loginLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lb_repete_senha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_repete_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spn_carga_horaria, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        lb_loginLayout.setVerticalGroup(
            lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_usuario)
                        .addComponent(lb_carga_horaria)
                        .addComponent(spn_carga_horaria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_senha)
                    .addGroup(lb_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_repete_senha)
                        .addComponent(tf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_repete_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pn_contato.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));
        pn_contato.setOpaque(false);

        lb_telefone.setText("Telefone:");

        lb_celular.setText("Celular:");

        lb_email.setText("E-mail:");

        javax.swing.GroupLayout pn_contatoLayout = new javax.swing.GroupLayout(pn_contato);
        pn_contato.setLayout(pn_contatoLayout);
        pn_contatoLayout.setHorizontalGroup(
            pn_contatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_contatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_contatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_contatoLayout.createSequentialGroup()
                        .addComponent(lb_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_contatoLayout.createSequentialGroup()
                        .addComponent(lb_telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lb_celular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        pn_contatoLayout.setVerticalGroup(
            pn_contatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_contatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_telefone)
                    .addComponent(lb_celular)
                    .addComponent(tf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_contatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_email)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_dados_pessoais.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        pn_dados_pessoais.setOpaque(false);

        lb_nome.setText("Nome:");

        lb_sexo.setText("Sexo:");

        lb_cpf.setText("CPF:");

        lb_data_nasc.setText("Data Nasc.:");

        javax.swing.GroupLayout pn_dados_pessoaisLayout = new javax.swing.GroupLayout(pn_dados_pessoais);
        pn_dados_pessoais.setLayout(pn_dados_pessoaisLayout);
        pn_dados_pessoaisLayout.setHorizontalGroup(
            pn_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dados_pessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_nome)
                    .addComponent(lb_cpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_data_nasc)
                    .addComponent(lb_sexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_data_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pn_dados_pessoaisLayout.setVerticalGroup(
            pn_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dados_pessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nome)
                    .addComponent(lb_sexo)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pn_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cpf)
                    .addComponent(lb_data_nasc)
                    .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_data_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pn_foto.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));
        pn_foto.setOpaque(false);

        btn_escolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escolherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_fotoLayout = new javax.swing.GroupLayout(pn_foto);
        pn_foto.setLayout(pn_fotoLayout);
        pn_fotoLayout.setHorizontalGroup(
            pn_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_fotoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_escolher, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pn_fotoLayout.setVerticalGroup(
            pn_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_fotoLayout.createSequentialGroup()
                .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_escolher, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn_localizacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Locallização"));
        pn_localizacao.setOpaque(false);

        lb_estado.setText("Estado:");
        lb_estado.setMaximumSize(new java.awt.Dimension(29, 14));
        lb_estado.setMinimumSize(new java.awt.Dimension(29, 14));

        lb_cidade.setText("Cidade:");

        lb_endereco.setText("Endereço:");

        lb_numero.setText("Número:");

        lb_cep.setText("CEP:");

        lb_descricao.setText("Desc. End.:");

        cb_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_localizacaoLayout = new javax.swing.GroupLayout(pn_localizacao);
        pn_localizacao.setLayout(pn_localizacaoLayout);
        pn_localizacaoLayout.setHorizontalGroup(
            pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_localizacaoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_endereco, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(cb_estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_localizacaoLayout.createSequentialGroup()
                        .addComponent(lb_cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pn_localizacaoLayout.createSequentialGroup()
                        .addComponent(lb_descricao)
                        .addGap(5, 5, 5)))
                .addGroup(pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(tf_desc_end, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_numero)
                    .addComponent(lb_cep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_localizacaoLayout.setVerticalGroup(
            pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_localizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cidade)
                    .addComponent(lb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_numero)
                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_localizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_endereco)
                    .addComponent(tf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_descricao)
                    .addComponent(tf_desc_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_cep)
                    .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pn_cad_vendedorLayout = new javax.swing.GroupLayout(pn_cad_vendedor);
        pn_cad_vendedor.setLayout(pn_cad_vendedorLayout);
        pn_cad_vendedorLayout.setHorizontalGroup(
            pn_cad_vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cad_vendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_cad_vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_cad_vendedorLayout.createSequentialGroup()
                        .addComponent(pn_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cad_vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn_dados_pessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_cad_vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lb_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_localizacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pn_cad_vendedorLayout.setVerticalGroup(
            pn_cad_vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cad_vendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_cad_vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_cad_vendedorLayout.createSequentialGroup()
                        .addComponent(pn_dados_pessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_localizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_cad_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_cad_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_escolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escolherActionPerformed
        abrirFileChooser();
    }//GEN-LAST:event_btn_escolherActionPerformed

    private void cb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_estadoActionPerformed
        verificaEstado();
    }//GEN-LAST:event_cb_estadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_escolher;
    private com.hermes.components.HMSelections.HMComboBox cb_cidade;
    private com.hermes.components.HMSelections.HMComboBox cb_estado;
    private com.hermes.components.HMSelections.HMComboBox cb_sexo;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel lb_carga_horaria;
    private javax.swing.JLabel lb_celular;
    private javax.swing.JLabel lb_cep;
    private javax.swing.JLabel lb_cidade;
    private javax.swing.JLabel lb_cpf;
    private javax.swing.JLabel lb_data_nasc;
    private javax.swing.JLabel lb_descricao;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_endereco;
    private javax.swing.JLabel lb_estado;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JPanel lb_login;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_numero;
    private javax.swing.JLabel lb_repete_senha;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JLabel lb_sexo;
    private javax.swing.JLabel lb_telefone;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPanel pn_cad_vendedor;
    private javax.swing.JPanel pn_contato;
    private javax.swing.JPanel pn_dados_pessoais;
    private javax.swing.JPanel pn_foto;
    private javax.swing.JPanel pn_localizacao;
    private javax.swing.JSpinner spn_carga_horaria;
    private com.hermes.components.HMFields.HMFormattedTextField tf_celular;
    private com.hermes.components.HMFields.HMFormattedTextField tf_cep;
    private com.hermes.components.HMFields.HMFormattedTextField tf_cpf;
    private com.hermes.components.HMFields.HMFormattedTextField tf_data_nasc;
    private com.hermes.components.HMFields.HMTextField tf_desc_end;
    private com.hermes.components.HMFields.HMTextField tf_email;
    private com.hermes.components.HMFields.HMTextField tf_endereco;
    private com.hermes.components.HMFields.HMTextField tf_nome;
    private com.hermes.components.HMFields.HMTextField tf_numero;
    private com.hermes.components.HMFields.HMPasswordField tf_repete_senha;
    private com.hermes.components.HMFields.HMPasswordField tf_senha;
    private com.hermes.components.HMFields.HMFormattedTextField tf_telefone;
    private com.hermes.components.HMFields.HMTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
