package hermes.client.view.register;

import com.hermes.components.HMFrames.HMInternalFrame;
import hermes.client.controll.produto.AplicacaoController;
import hermes.client.listener.produto.Dispatcher;
import javax.swing.JOptionPane;

/**
 *
 * @author iury
 */
public class RegisterAplicacao extends HMInternalFrame {
    
    private AplicacaoController controller;

    public void addAplicacao() {
        if (!tp_aplicacao.getText().isEmpty()) {
            Dispatcher.getInstance().dispatchObject(controller.buildAplicacao(tp_aplicacao.getText()));
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Você não pode inserir uma aplicação vazia!");
        }
    }

    public void cancelar() {
        int i = JOptionPane.showConfirmDialog(null, "Você tem certeza que quer cancelar essa operação?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }

    public RegisterAplicacao() {
        initComponents();
        setSize(359, 226);
        controller = new AplicacaoController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_aplicacao = new javax.swing.JPanel();
        lb_aplicacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp_aplicacao = new javax.swing.JTextPane();
        btn_add = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setTitle("Aplicação");

        lb_aplicacao.setText("Nova Aplicação:");

        jScrollPane1.setViewportView(tp_aplicacao);

        btn_add.setText("OK");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_aplicacaoLayout = new javax.swing.GroupLayout(pn_aplicacao);
        pn_aplicacao.setLayout(pn_aplicacaoLayout);
        pn_aplicacaoLayout.setHorizontalGroup(
            pn_aplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_aplicacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_aplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_aplicacaoLayout.createSequentialGroup()
                        .addComponent(lb_aplicacao)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_aplicacaoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(pn_aplicacaoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        pn_aplicacaoLayout.setVerticalGroup(
            pn_aplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_aplicacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_aplicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_aplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_cancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_aplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_aplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        addAplicacao();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_aplicacao;
    private javax.swing.JPanel pn_aplicacao;
    private javax.swing.JTextPane tp_aplicacao;
    // End of variables declaration//GEN-END:variables
}
