package hermes.client.view.register;

import com.hermes.components.HMFrames.HMInternalFrame;
import hermes.client.controll.frame.DesktopController;
import hermes.client.controll.tipoProduto.TipoProdutoController;
import hermes.ejb.entidades.Equipamento;
import hermes.ejb.entidades.TipoProduto;
import java.awt.Dimension;

public class RegisterEquipamento extends HMInternalFrame {

    private RegisterCliente frameCliente;
    private Equipamento equipamento;
    private Integer rowIndex;
    private boolean alterar;

    public void initFields() {
        tf_marca.setObrigatory(true);
        tf_nome.setObrigatory(true);
        cb_tipo.setValues(new TipoProdutoController().getTipos());
    }

    public void addEquipamento() {
        equipamento.setDescricao(tp_descricao.getText());
        equipamento.setIdTipoProduto((TipoProduto) cb_tipo.getSelectedItem());
        equipamento.setMarca(tf_marca.getText());
        equipamento.setNome(tf_nome.getText());
        if (rowIndex == -1) {
            frameCliente.addEquipamento(equipamento);
        } else {
            frameCliente.alterEquipamento(equipamento, rowIndex);
        }
        dispose();
    }

    public void setOwnerFrame(RegisterCliente frame) {
        this.frameCliente = frame;
    }

    public void buildEquipamento() {
        tf_nome.setText(equipamento.getNome());
        tf_marca.setText(equipamento.getMarca());
        cb_tipo.setSelectedItem(equipamento.getIdTipoProduto());
        tp_descricao.setText(equipamento.getDescricao());
        tf_nome.setValid(true);
        tf_marca.setValid(true);
    }

    public RegisterEquipamento() {
        initComponents();
        initFields();
        equipamento = new Equipamento();
        rowIndex = -1;
    }

    public RegisterEquipamento(Equipamento equipamento, int rowIndex) {
        initComponents();
        initFields();
        this.equipamento = equipamento;
        this.rowIndex = rowIndex;
        buildEquipamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_equipamento = new javax.swing.JPanel();
        pn_dados = new javax.swing.JPanel();
        label_nome = new javax.swing.JLabel();
        label_marca = new javax.swing.JLabel();
        label_tipo = new javax.swing.JLabel();
        cb_tipo = new com.hermes.components.HMSelections.HMComboBox();
        tf_marca = new com.hermes.components.HMFields.HMTextField();
        tf_nome = new com.hermes.components.HMFields.HMTextField();
        pn_descricao = new javax.swing.JPanel();
        scroll_desc = new javax.swing.JScrollPane();
        tp_descricao = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Novo Equipamento");

        pn_equipamento.setOpaque(false);

        pn_dados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        pn_dados.setOpaque(false);

        label_nome.setText("Nome:");

        label_marca.setText("Marca:");

        label_tipo.setText("Tipo:");

        javax.swing.GroupLayout pn_dadosLayout = new javax.swing.GroupLayout(pn_dados);
        pn_dados.setLayout(pn_dadosLayout);
        pn_dadosLayout.setHorizontalGroup(
            pn_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_tipo)
                    .addComponent(label_nome)
                    .addComponent(label_marca))
                .addGap(18, 18, 18)
                .addGroup(pn_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pn_dadosLayout.setVerticalGroup(
            pn_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dadosLayout.createSequentialGroup()
                .addGroup(pn_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_marca)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tipo)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pn_descricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        pn_descricao.setOpaque(false);

        scroll_desc.setViewportView(tp_descricao);

        javax.swing.GroupLayout pn_descricaoLayout = new javax.swing.GroupLayout(pn_descricao);
        pn_descricao.setLayout(pn_descricaoLayout);
        pn_descricaoLayout.setHorizontalGroup(
            pn_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_descricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_desc, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_descricaoLayout.setVerticalGroup(
            pn_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_descricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_equipamentoLayout = new javax.swing.GroupLayout(pn_equipamento);
        pn_equipamento.setLayout(pn_equipamentoLayout);
        pn_equipamentoLayout.setHorizontalGroup(
            pn_equipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_equipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_equipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_equipamentoLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        pn_equipamentoLayout.setVerticalGroup(
            pn_equipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_equipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_equipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addEquipamento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hermes.components.HMSelections.HMComboBox cb_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel label_marca;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_tipo;
    private javax.swing.JPanel pn_dados;
    private javax.swing.JPanel pn_descricao;
    private javax.swing.JPanel pn_equipamento;
    private javax.swing.JScrollPane scroll_desc;
    private com.hermes.components.HMFields.HMTextField tf_marca;
    private com.hermes.components.HMFields.HMTextField tf_nome;
    private javax.swing.JTextPane tp_descricao;
    // End of variables declaration//GEN-END:variables
}
