package hermes.client.view.select;

import hermes.client.view.register.RegisterOrdemServico;
import com.hermes.components.HMFrames.HMInternalFrame;
import com.hermes.components.HMTables.HMMultipleClassesTableModel;
import hermes.client.controll.produto.ProdutoController;
import hermes.client.dao.ProdutoBean;
import hermes.ejb.entidades.Estoque;
import hermes.ejb.entidades.ItemOrdemServico;
import hermes.ejb.entidades.Produto;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author iury
 */
public class SelectProduto extends HMInternalFrame {

    private String[] colunas = {"", "", "Nome", "Med. Int.", "Localização", "Código", "Med. Ext.", "", "Unidade", "Tipo", "", "", "", "", "", "", "", "", "", "Qtdade", "", "Valor Venda", "", "Custo", ""};
    private String[] ocultas = {"serialVersionUID", "idProduto", "foto", "aplicacaoList", "itemOrdemVendaList", "descricaoList", "itemOrdemFabricacaoList", "ordemDeCompraList",
        "estoqueList", "itemOrdemServicoList", "idEstoque", "idProduto", "idAtivo", "dthAlteracao", "medidaInterna", "medidaExterna", "localizacao"};
    private List<Class<?>> classes;
    private List<Estoque> produtos;
    private RegisterOrdemServico os;
    private Estoque selectedProduto;
    private List<ItemOrdemServico> itens;

    public void initFields() {
        //TEXT FIELDS
        tf_pesquisa.setStaticIcon("zoom.png", 20, 20);
        //TABLE
        List<List<?>> listas = new ArrayList();
        classes = new ArrayList();
        try {
            produtos = new ProdutoBean().consultaValidIdAtivoEstoques();
            List<Produto> p = new ArrayList();
            List<Estoque> ps = new ArrayList();
            for (Estoque estoque : produtos) {
                for (ItemOrdemServico item : itens) {
                    if (item.getIdProduto().equals(estoque.getIdProduto())) {
                        estoque.setQuantidade(estoque.getQuantidade() - item.getQuantidade().longValue());
                    }
                }
                if (estoque.getQuantidade() > 0) {
                    p.add(estoque.getIdProduto());
                    ps.add(estoque);
                }
            }
            listas.add(p);
            listas.add(ps);
            produtos = ps;
            classes.add(Produto.class);
            classes.add(Estoque.class);
        } catch (Exception ex) {
            Logger.getLogger(SelectProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbl_pesquisa.setModelo(new HMMultipleClassesTableModel(listas, classes, colunas));
        tbl_pesquisa.ocultarColunas(ocultas);
        tf_produto.setEditable(false);
        tf_produto.setEnabled(false);
    }

    public void onKeyReleased() {
        new Thread() {
            public void run() {
                tbl_pesquisa.getModeloMC().setListas(new ProdutoController().filtraProdutos(tf_pesquisa.getText(), produtos));
            }
        }.start();
    }

    public void showProduto() {
        Estoque e = null;
        List<?> l = tbl_pesquisa.getSelectedItemMC();
        for (Object ob : l) {
            if (ob instanceof Estoque) {
                e = (Estoque) ob;
            }
        }
        try {
            tf_produto.setText(e.getIdProduto().getNome() + " - R$" + e.getValorVenda());
            selectedProduto = e;
            int max = (int) e.getQuantidade();
            SpinnerNumberModel model = new SpinnerNumberModel(1, 1, max, 1);
            spn_quantidade.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(SelectProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void selectProduto() {
        if (!tf_produto.getText().isEmpty()) {
            try {
                ItemOrdemServico ios = new ItemOrdemServico();
                ios.setIdProduto(selectedProduto.getIdProduto());
                Double value = Double.valueOf(spn_quantidade.getValue().toString());
                ios.setQuantidade(BigDecimal.valueOf(value));
                os.addProduto(ios);
                this.dispose();
            } catch (Exception e) {
                Logger.getLogger(SelectProduto.class.getName()).log(Level.SEVERE, null, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto!");
        }
    }

    public SelectProduto(RegisterOrdemServico os, List<ItemOrdemServico> itens) {
        initComponents();
        this.os = os;
        this.itens = itens;
        new Thread() {
            public void run() {
                initFields();
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_pesquisa = new javax.swing.JPanel();
        pn_cliente = new javax.swing.JPanel();
        tf_produto = new javax.swing.JTextField();
        btn_ok = new javax.swing.JButton();
        spn_quantidade = new javax.swing.JSpinner();
        pn_filtros = new javax.swing.JPanel();
        tf_pesquisa = new com.hermes.components.HMFields.HMTextField();
        pn_resultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesquisa = new com.hermes.components.HMTables.HMTable();

        pn_pesquisa.setOpaque(false);

        pn_cliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipamento"));
        pn_cliente.setOpaque(false);

        tf_produto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btn_ok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        spn_quantidade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout pn_clienteLayout = new javax.swing.GroupLayout(pn_cliente);
        pn_cliente.setLayout(pn_clienteLayout);
        pn_clienteLayout.setHorizontalGroup(
            pn_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_clienteLayout.setVerticalGroup(
            pn_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tf_produto, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addComponent(btn_ok, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
            .addComponent(spn_quantidade, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pn_filtros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        pn_filtros.setOpaque(false);

        tf_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_pesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pn_filtrosLayout = new javax.swing.GroupLayout(pn_filtros);
        pn_filtros.setLayout(pn_filtrosLayout);
        pn_filtrosLayout.setHorizontalGroup(
            pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_filtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_filtrosLayout.setVerticalGroup(
            pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_filtrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pn_resultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        pn_resultados.setOpaque(false);

        tbl_pesquisa.setForeground(new java.awt.Color(0, 0, 0));
        tbl_pesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pesquisa);

        javax.swing.GroupLayout pn_resultadosLayout = new javax.swing.GroupLayout(pn_resultados);
        pn_resultados.setLayout(pn_resultadosLayout);
        pn_resultadosLayout.setHorizontalGroup(
            pn_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pn_resultadosLayout.setVerticalGroup(
            pn_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pn_pesquisaLayout = new javax.swing.GroupLayout(pn_pesquisa);
        pn_pesquisa.setLayout(pn_pesquisaLayout);
        pn_pesquisaLayout.setHorizontalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pn_filtros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_resultados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_pesquisaLayout.setVerticalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesquisaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pn_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        selectProduto();
    }//GEN-LAST:event_btn_okActionPerformed

    private void tf_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisaKeyReleased
        onKeyReleased();
    }//GEN-LAST:event_tf_pesquisaKeyReleased

    private void tbl_pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pesquisaMouseClicked
        showProduto();
        if (evt.getClickCount() == 2) {
            selectProduto();
        }
    }//GEN-LAST:event_tbl_pesquisaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_cliente;
    private javax.swing.JPanel pn_filtros;
    private javax.swing.JPanel pn_pesquisa;
    private javax.swing.JPanel pn_resultados;
    private javax.swing.JSpinner spn_quantidade;
    private com.hermes.components.HMTables.HMTable tbl_pesquisa;
    private com.hermes.components.HMFields.HMTextField tf_pesquisa;
    private javax.swing.JTextField tf_produto;
    // End of variables declaration//GEN-END:variables
}
