package hermes.client.view.search;

import com.hermes.components.HMFrames.HMInternalFrame;
import com.hermes.components.HMTables.HMMultipleClassesTableModel;
import hermes.client.controll.frame.DesktopController;
import hermes.client.controll.mecanico.MecanicoController;
import hermes.client.main.Main;
import hermes.client.view.register.RegisterMecanico;
import hermes.ejb.entidades.Mecanico;
import hermes.ejb.entidades.MecanicoInfo;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author iury
 */
public class SearchMecanico extends javax.swing.JPanel {

    private String[] colunas = {"", "", "", "", "Nome", "CPF", "Sexo", "Data Nasc.", "", "", "", "Valor Hora", "", "Endereço", "Telefone", "Celular", "Carga Hor.", "End. Desc.", "", "Email", "", "Cidade", "Estado", "CEP", ""};
    private String[] ocultas = {"mecanicoOrdemFabricacaoCollection", "mecanicoOrdemServicoCollection", "serialVersionUID", "idMecanico", "mecanicoInfoList", "idMecanicoInfo", "idAtivo", "dthAlteracao", "foto"};
    private List<Class<?>> classes;
    private List<MecanicoInfo> mecanicos;

    public void initFields() {
        //TEXT FIELDS
        tf_pesquisa.setStaticIcon("zoom.png", 20, 20);
        //TABLE
        List<List<?>> listas = new ArrayList();
        classes = new ArrayList();
        try {
            List<Mecanico> m = new ArrayList();
            mecanicos = new MecanicoController().consultaMecanicoInfosByIdAtivo();
            for (MecanicoInfo minfo : mecanicos) {
                m.add(minfo.getIdMecanico());
            }
            listas.add(m);
            listas.add(mecanicos);
            classes.add(Mecanico.class);
            classes.add(MecanicoInfo.class);
        } catch (Exception ex) {
            Logger.getLogger(SearchMecanico.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbl_pesquisa.setModelo(new HMMultipleClassesTableModel(listas, classes, colunas));
        tbl_pesquisa.ocultarColunas(ocultas);
    }

    public void onKeyReleased() {
        new Thread() {
            public void run() {
                tbl_pesquisa.getModeloMC().setListas(new MecanicoController().filtraMecanicos(tf_pesquisa.getText(), mecanicos));
            }
        }.start();
    }

    public void rebuildMecanico() {
        MecanicoInfo mi = null;
        List<?> l = tbl_pesquisa.getSelectedItemMC();
        for (Object ob : l) {
            if (ob instanceof MecanicoInfo) {
                mi = (MecanicoInfo) ob;
            }
        }
        try {
            RegisterMecanico cm = new RegisterMecanico(mi, this, tbl_pesquisa.getSelectedRow());
            HMInternalFrame frame = new HMInternalFrame();
            frame.setSize(cm.getSize().width + 30, cm.getSize().height);
            frame.add(cm);
            frame.setVisible(true);
            Main.desktop.addInternalFrame(frame);
        } catch (Exception ex) {
            Logger.getLogger(RegisterMecanico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void alterObject(List<?> lista, int index) {
        tbl_pesquisa.alterObjectMC(lista, index);
    }

    public SearchMecanico() {
        initComponents();
        setSize(940, 580);
        new Thread() {
            public void run() {
                initFields();
                pn_pesquisa.setOpaque(false);
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_pesquisa = new javax.swing.JPanel();
        pn_filtros = new javax.swing.JPanel();
        tf_pesquisa = new com.hermes.components.HMFields.HMTextField();
        pn_resultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesquisa = new com.hermes.components.HMTables.HMTable();

        setOpaque(false);

        pn_pesquisa.setOpaque(false);
        pn_pesquisa.setPreferredSize(new java.awt.Dimension(1100, 580));

        pn_filtros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        pn_filtros.setOpaque(false);

        tf_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_pesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pn_filtrosLayout = new javax.swing.GroupLayout(pn_filtros);
        pn_filtros.setLayout(pn_filtrosLayout);
        pn_filtrosLayout.setHorizontalGroup(
            pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_filtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_filtrosLayout.setVerticalGroup(
            pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_filtrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pn_resultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        pn_resultados.setOpaque(false);

        tbl_pesquisa.setForeground(new java.awt.Color(0, 0, 0));
        tbl_pesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pesquisa);

        javax.swing.GroupLayout pn_resultadosLayout = new javax.swing.GroupLayout(pn_resultados);
        pn_resultados.setLayout(pn_resultadosLayout);
        pn_resultadosLayout.setHorizontalGroup(
            pn_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pn_resultadosLayout.setVerticalGroup(
            pn_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_pesquisaLayout = new javax.swing.GroupLayout(pn_pesquisa);
        pn_pesquisa.setLayout(pn_pesquisaLayout);
        pn_pesquisaLayout.setHorizontalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pn_resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_filtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_pesquisaLayout.setVerticalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisaKeyReleased
        onKeyReleased();
    }//GEN-LAST:event_tf_pesquisaKeyReleased

    private void tbl_pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pesquisaMouseClicked
        if (evt.getClickCount() == 2) {
            rebuildMecanico();
        }
    }//GEN-LAST:event_tbl_pesquisaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_filtros;
    private javax.swing.JPanel pn_pesquisa;
    private javax.swing.JPanel pn_resultados;
    private com.hermes.components.HMTables.HMTable tbl_pesquisa;
    private com.hermes.components.HMFields.HMTextField tf_pesquisa;
    // End of variables declaration//GEN-END:variables
}
