package hermes.client.view.search;

import hermes.client.view.register.RegisterCliente;
import com.hermes.components.HMFrames.HMInternalFrame;
import com.hermes.components.HMTables.HMMultipleClassesTableModel;
import hermes.client.controll.cliente.ClienteController;
import hermes.client.dao.ClienteBean;
import hermes.client.main.Main;
import hermes.ejb.entidades.Cliente;
import hermes.ejb.entidades.ClienteInfo;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author iury
 */
public class SearchCliente extends javax.swing.JPanel {

    private String[] colunas = {"", "", "Nome", "CPF", "CNPJ", "Sexo", "Data Nasc.", "Tipo Pessoa", "", "", "", "", "", "Endereco", "Telefone", "Celular",
        "", "Desc. End.", "", "Email", "Credibilidade", "Cidade", "Estado", "CEP", ""};
    private String[] ocultas = {"ordemDeVendaList", "clienteInfoList", "serialVersionUID", "idCliente", "equipamentoList", "idClienteInfo", "idAtivo", "dthAlteracao", "idCliente"};
    private List<Class<?>> classes;
    private List<ClienteInfo> clientes;

    public void initFields() {
        //TEXT FIELDS
        tf_pesquisa.setStaticIcon("zoom.png", 20, 20);
        //TABLE
        List<List<?>> listas = new ArrayList();
        classes = new ArrayList();
        try {
            List<Cliente> c = new ArrayList();
            clientes = new ClienteBean().consultaClienteInfosByIdAtivo();
            for (ClienteInfo cinfo : clientes) {
                c.add(cinfo.getIdCliente());
            }
            listas.add(c);
            listas.add(clientes);
            classes.add(Cliente.class);
            classes.add(ClienteInfo.class);
        } catch (Exception ex) {
            Logger.getLogger(SearchCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbl_pesquisa.setModelo(new HMMultipleClassesTableModel(listas, classes, colunas));
        tbl_pesquisa.ocultarColunas(ocultas);
    }

    public void onKeyReleased() {
        new Thread() {
            public void run() {
                tbl_pesquisa.getModeloMC().setListas(new ClienteController().filtraClientes(tf_pesquisa.getText(), clientes));
            }
        }.start();
    }

    public void rebuildCliente() {
        ClienteInfo ci = null;
        List<?> l = tbl_pesquisa.getSelectedItemMC();
        for (Object ob : l) {
            if (ob instanceof ClienteInfo) {
                ci = (ClienteInfo) ob;
            }
        }
        try {
            RegisterCliente cc = new RegisterCliente();
            HMInternalFrame frame = new HMInternalFrame();
            frame.setSize(cc.getSize().width + 30, cc.getSize().height);
            frame.add(cc);
            Main.desktop.addInternalFrame(frame);
        } catch (Exception ex) {
            Logger.getLogger(RegisterCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void alterObject(List<?> lista, int index) {
        tbl_pesquisa.alterObjectMC(lista, index);
    }

    public SearchCliente() {
        initComponents();
        setSize(1100, 580);
        new Thread() {
            public void run() {
                initFields();
                pn_pesquisa.setOpaque(false);
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_pesquisa = new javax.swing.JPanel();
        pn_filtros = new javax.swing.JPanel();
        tf_pesquisa = new com.hermes.components.HMFields.HMTextField();
        chk_nome = new javax.swing.JCheckBox();
        chk_cpf = new javax.swing.JCheckBox();
        chk_cnpj = new javax.swing.JCheckBox();
        chk_sexo = new javax.swing.JCheckBox();
        chk_tipo_pessoa = new javax.swing.JCheckBox();
        chk_endereco = new javax.swing.JCheckBox();
        chk_telefone = new javax.swing.JCheckBox();
        chk_celular = new javax.swing.JCheckBox();
        chk_desc_end = new javax.swing.JCheckBox();
        chk_email = new javax.swing.JCheckBox();
        chk_cidade = new javax.swing.JCheckBox();
        chk_estado = new javax.swing.JCheckBox();
        chk_cep = new javax.swing.JCheckBox();
        pn_resultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesquisa = new com.hermes.components.HMTables.HMTable();

        setOpaque(false);

        pn_pesquisa.setOpaque(false);
        pn_pesquisa.setPreferredSize(new java.awt.Dimension(1100, 580));

        pn_filtros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        pn_filtros.setOpaque(false);

        tf_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_pesquisaKeyReleased(evt);
            }
        });

        chk_nome.setText("Nome");
        chk_nome.setOpaque(false);

        chk_cpf.setText("CPF");
        chk_cpf.setOpaque(false);

        chk_cnpj.setText("CNPJ");
        chk_cnpj.setOpaque(false);

        chk_sexo.setText("Sexo");
        chk_sexo.setOpaque(false);

        chk_tipo_pessoa.setText("Tipo Pessoa");
        chk_tipo_pessoa.setOpaque(false);

        chk_endereco.setText("Endereço");
        chk_endereco.setOpaque(false);

        chk_telefone.setText("Telefone");
        chk_telefone.setOpaque(false);

        chk_celular.setText("Celular");
        chk_celular.setOpaque(false);

        chk_desc_end.setText("Desc. End.");
        chk_desc_end.setOpaque(false);

        chk_email.setText("Email");
        chk_email.setOpaque(false);

        chk_cidade.setText("Cidade");
        chk_cidade.setOpaque(false);

        chk_estado.setText("Estado");
        chk_estado.setOpaque(false);

        chk_cep.setText("CEP");
        chk_cep.setOpaque(false);

        javax.swing.GroupLayout pn_filtrosLayout = new javax.swing.GroupLayout(pn_filtros);
        pn_filtros.setLayout(pn_filtrosLayout);
        pn_filtrosLayout.setHorizontalGroup(
            pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_filtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_filtrosLayout.createSequentialGroup()
                        .addComponent(chk_nome)
                        .addGap(18, 18, 18)
                        .addComponent(chk_cpf)
                        .addGap(18, 18, 18)
                        .addComponent(chk_cnpj)
                        .addGap(18, 18, 18)
                        .addComponent(chk_sexo)
                        .addGap(18, 18, 18)
                        .addComponent(chk_tipo_pessoa)
                        .addGap(18, 18, 18)
                        .addComponent(chk_endereco)
                        .addGap(18, 18, 18)
                        .addComponent(chk_desc_end)
                        .addGap(18, 18, 18)
                        .addComponent(chk_telefone)
                        .addGap(18, 18, 18)
                        .addComponent(chk_celular)
                        .addGap(18, 18, 18)
                        .addComponent(chk_email)
                        .addGap(18, 18, 18)
                        .addComponent(chk_cidade)
                        .addGap(18, 18, 18)
                        .addComponent(chk_estado)
                        .addGap(18, 18, 18)
                        .addComponent(chk_cep)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tf_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_filtrosLayout.setVerticalGroup(
            pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_filtrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_nome)
                    .addComponent(chk_cpf)
                    .addComponent(chk_cnpj)
                    .addComponent(chk_sexo)
                    .addComponent(chk_tipo_pessoa)
                    .addComponent(chk_endereco)
                    .addComponent(chk_telefone)
                    .addComponent(chk_celular)
                    .addComponent(chk_desc_end)
                    .addComponent(chk_email)
                    .addComponent(chk_cidade)
                    .addComponent(chk_estado)
                    .addComponent(chk_cep)))
        );

        pn_resultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        pn_resultados.setOpaque(false);

        tbl_pesquisa.setForeground(new java.awt.Color(0, 0, 0));
        tbl_pesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pesquisa);

        javax.swing.GroupLayout pn_resultadosLayout = new javax.swing.GroupLayout(pn_resultados);
        pn_resultados.setLayout(pn_resultadosLayout);
        pn_resultadosLayout.setHorizontalGroup(
            pn_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_resultadosLayout.setVerticalGroup(
            pn_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout pn_pesquisaLayout = new javax.swing.GroupLayout(pn_pesquisa);
        pn_pesquisa.setLayout(pn_pesquisaLayout);
        pn_pesquisaLayout.setHorizontalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pn_resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_filtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_pesquisaLayout.setVerticalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_filtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisaKeyReleased
        onKeyReleased();
    }//GEN-LAST:event_tf_pesquisaKeyReleased

    private void tbl_pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pesquisaMouseClicked
        if (evt.getClickCount() == 2) {
            rebuildCliente();
        }
    }//GEN-LAST:event_tbl_pesquisaMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk_celular;
    private javax.swing.JCheckBox chk_cep;
    private javax.swing.JCheckBox chk_cidade;
    private javax.swing.JCheckBox chk_cnpj;
    private javax.swing.JCheckBox chk_cpf;
    private javax.swing.JCheckBox chk_desc_end;
    private javax.swing.JCheckBox chk_email;
    private javax.swing.JCheckBox chk_endereco;
    private javax.swing.JCheckBox chk_estado;
    private javax.swing.JCheckBox chk_nome;
    private javax.swing.JCheckBox chk_sexo;
    private javax.swing.JCheckBox chk_telefone;
    private javax.swing.JCheckBox chk_tipo_pessoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_filtros;
    private javax.swing.JPanel pn_pesquisa;
    private javax.swing.JPanel pn_resultados;
    private com.hermes.components.HMTables.HMTable tbl_pesquisa;
    private com.hermes.components.HMFields.HMTextField tf_pesquisa;
    // End of variables declaration//GEN-END:variables
}
