package hermes.client.view.toolbar;

import com.hermes.components.HMFrames.HMInternalFrame;
import com.hermes.components.HMFrames.HMPanel;
import hermes.client.controll.frame.DesktopController;
import hermes.client.view.register.RegisterCliente;
import hermes.client.view.register.RegisterFornecedor;
import hermes.client.view.register.RegisterMecanico;
import hermes.client.view.register.RegisterOrdemServico;
import hermes.client.view.register.RegisterProduto;
import hermes.client.view.register.RegisterProdutoFabricado;
import hermes.client.view.register.RegisterTipoProduto;
import hermes.client.view.register.RegisterVendedor;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author iury
 */
public class Novo extends HMInternalFrame {

    private HMPanel panel;

    @Override
    public HMPanel getHMPanel() {
        return this.panel;
    }

    public void newCadastro(JButton btn, Class classe, String title) {
        deopaqueButtons();
        pn_cadastro.removeAll();
        btn.setBackground(new Color(0, 204, 255));
        btn.setOpaque(true);
        Object ob = new Object();
        try {
            ob = classe.newInstance();
        } catch (InstantiationException ex) {
            Logger.getLogger(Novo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Novo.class.getName()).log(Level.SEVERE, null, ex);
        }
        ((HMPanel) ob).setVisible(true);
        this.panel = ((HMPanel) ob);
        pn_cadastro.add((HMPanel) ob);
        updateUI();
        setBackground(new Color(224, 249, 252));
        setTitle(title);
        setFrameIcon(btn.getIcon());
        int witdh = ((HMPanel) ob).getSize().width;
        int height = ((HMPanel) ob).getSize().height;
        pn_cadastro.setSize(witdh, height);
        setSize(witdh + 140, height + 40);
    }

    public void deopaqueButtons() {
        Component[] componentes = toolbar_cadastro.getComponents();
        String classe;
        for (int contador = 0; contador < componentes.length; contador++) {
            classe = componentes[contador].getClass().getName();
            try {
                if (classe.contains("JButton")) {
                    ((JButton) componentes[contador]).setOpaque(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Não foi possível resetar os botões!");
            }
        }
    }

    public Novo() {
        initComponents();
        sp_cadastro.setViewportView(toolbar_cadastro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar_cadastro = new javax.swing.JToolBar();
        btn_cadastro_produto = new javax.swing.JButton();
        btn_cadastro_os = new javax.swing.JButton();
        btn_cadastro_ov = new javax.swing.JButton();
        btn_cadastro_of = new javax.swing.JButton();
        btn_cadastro_oc = new javax.swing.JButton();
        btn_cadastro_cliente = new javax.swing.JButton();
        btn_cadastro_fornecedor = new javax.swing.JButton();
        btn_cadastro_vendedor = new javax.swing.JButton();
        btn_cadastro_mecanico = new javax.swing.JButton();
        btn_cadastro_tipo_produto = new javax.swing.JButton();
        btn_cadastro_produto_fabricado = new javax.swing.JButton();
        pn_cadastro = new javax.swing.JPanel();
        sp_cadastro = new javax.swing.JScrollPane();

        toolbar_cadastro.setBackground(new java.awt.Color(196, 240, 252));
        toolbar_cadastro.setFloatable(false);
        toolbar_cadastro.setOrientation(javax.swing.SwingConstants.VERTICAL);
        toolbar_cadastro.setRollover(true);
        toolbar_cadastro.setAutoscrolls(true);

        btn_cadastro_produto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cadastro_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hammer_add.png"))); // NOI18N
        btn_cadastro_produto.setText("Produto");
        btn_cadastro_produto.setFocusable(false);
        btn_cadastro_produto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_produto.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_produto.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_produto.setOpaque(false);
        btn_cadastro_produto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cadastro_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_produtoActionPerformed(evt);
            }
        });
        toolbar_cadastro.add(btn_cadastro_produto);

        btn_cadastro_os.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cadastro_os.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard_add.png"))); // NOI18N
        btn_cadastro_os.setText("Ordem Serviço");
        btn_cadastro_os.setFocusable(false);
        btn_cadastro_os.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_os.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_os.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_os.setOpaque(false);
        btn_cadastro_os.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cadastro_os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_osActionPerformed(evt);
            }
        });
        toolbar_cadastro.add(btn_cadastro_os);

        btn_cadastro_ov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cadastro_ov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/certificate_add.png"))); // NOI18N
        btn_cadastro_ov.setText("Ordem Venda");
        btn_cadastro_ov.setFocusable(false);
        btn_cadastro_ov.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_ov.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_ov.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_ov.setOpaque(false);
        btn_cadastro_ov.setPreferredSize(new java.awt.Dimension(89, 89));
        btn_cadastro_ov.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar_cadastro.add(btn_cadastro_ov);

        btn_cadastro_of.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cadastro_of.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_add.png"))); // NOI18N
        btn_cadastro_of.setText("Ordem Fabric.");
        btn_cadastro_of.setFocusable(false);
        btn_cadastro_of.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_of.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_of.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_of.setOpaque(false);
        btn_cadastro_of.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar_cadastro.add(btn_cadastro_of);

        btn_cadastro_oc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping_basket_add.png"))); // NOI18N
        btn_cadastro_oc.setText("Ordem Compra");
        btn_cadastro_oc.setFocusable(false);
        btn_cadastro_oc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_oc.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_oc.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_oc.setOpaque(false);
        btn_cadastro_oc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar_cadastro.add(btn_cadastro_oc);

        btn_cadastro_cliente.setBackground(new java.awt.Color(0, 204, 255));
        btn_cadastro_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cadastro_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        btn_cadastro_cliente.setText("Cliente");
        btn_cadastro_cliente.setFocusable(false);
        btn_cadastro_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_cliente.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_cliente.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_cliente.setOpaque(false);
        btn_cadastro_cliente.setPreferredSize(new java.awt.Dimension(80, 85));
        btn_cadastro_cliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cadastro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_clienteActionPerformed(evt);
            }
        });
        toolbar_cadastro.add(btn_cadastro_cliente);

        btn_cadastro_fornecedor.setBackground(new java.awt.Color(196, 240, 252));
        btn_cadastro_fornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cadastro_fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/management_add.png"))); // NOI18N
        btn_cadastro_fornecedor.setText("Fornecedor");
        btn_cadastro_fornecedor.setFocusable(false);
        btn_cadastro_fornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_fornecedor.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_fornecedor.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_fornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cadastro_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_fornecedorActionPerformed(evt);
            }
        });
        toolbar_cadastro.add(btn_cadastro_fornecedor);

        btn_cadastro_vendedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cadastro_vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_add.png"))); // NOI18N
        btn_cadastro_vendedor.setText("Vendedor");
        btn_cadastro_vendedor.setFocusable(false);
        btn_cadastro_vendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_vendedor.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_vendedor.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_vendedor.setOpaque(false);
        btn_cadastro_vendedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cadastro_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_vendedorActionPerformed(evt);
            }
        });
        toolbar_cadastro.add(btn_cadastro_vendedor);

        btn_cadastro_mecanico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cadastro_mecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/technical_wrench_add.png"))); // NOI18N
        btn_cadastro_mecanico.setText("Mecânico");
        btn_cadastro_mecanico.setFocusable(false);
        btn_cadastro_mecanico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_mecanico.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_mecanico.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_mecanico.setOpaque(false);
        btn_cadastro_mecanico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cadastro_mecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_mecanicoActionPerformed(evt);
            }
        });
        toolbar_cadastro.add(btn_cadastro_mecanico);

        btn_cadastro_tipo_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/location_add.png"))); // NOI18N
        btn_cadastro_tipo_produto.setText("Tipo Produto");
        btn_cadastro_tipo_produto.setFocusable(false);
        btn_cadastro_tipo_produto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_tipo_produto.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_tipo_produto.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_tipo_produto.setOpaque(false);
        btn_cadastro_tipo_produto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cadastro_tipo_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_tipo_produtoActionPerformed(evt);
            }
        });
        toolbar_cadastro.add(btn_cadastro_tipo_produto);

        btn_cadastro_produto_fabricado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trophy_add.png"))); // NOI18N
        btn_cadastro_produto_fabricado.setText("Produto Fabric.");
        btn_cadastro_produto_fabricado.setFocusable(false);
        btn_cadastro_produto_fabricado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastro_produto_fabricado.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_produto_fabricado.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_cadastro_produto_fabricado.setOpaque(false);
        btn_cadastro_produto_fabricado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cadastro_produto_fabricado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_produto_fabricadoActionPerformed(evt);
            }
        });
        toolbar_cadastro.add(btn_cadastro_produto_fabricado);

        setBackground(new java.awt.Color(224, 249, 252));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        setTitle("Novo");
        setAutoscrolls(true);

        pn_cadastro.setOpaque(false);
        pn_cadastro.setPreferredSize(new java.awt.Dimension(729, 600));

        javax.swing.GroupLayout pn_cadastroLayout = new javax.swing.GroupLayout(pn_cadastro);
        pn_cadastro.setLayout(pn_cadastroLayout);
        pn_cadastroLayout.setHorizontalGroup(
            pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        pn_cadastroLayout.setVerticalGroup(
            pn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        sp_cadastro.setBackground(new java.awt.Color(102, 153, 255));
        sp_cadastro.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sp_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_clienteActionPerformed
        newCadastro(btn_cadastro_cliente, RegisterCliente.class, "Novo Cliente");
    }//GEN-LAST:event_btn_cadastro_clienteActionPerformed

    private void btn_cadastro_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_produtoActionPerformed
        newCadastro(btn_cadastro_produto, RegisterProduto.class, "Novo Produto");
    }//GEN-LAST:event_btn_cadastro_produtoActionPerformed

    private void btn_cadastro_mecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_mecanicoActionPerformed
        newCadastro(btn_cadastro_mecanico, RegisterMecanico.class, "Novo Mecânico");
    }//GEN-LAST:event_btn_cadastro_mecanicoActionPerformed

    private void btn_cadastro_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_vendedorActionPerformed
        newCadastro(btn_cadastro_vendedor, RegisterVendedor.class, "Novo Vendedor");
    }//GEN-LAST:event_btn_cadastro_vendedorActionPerformed

    private void btn_cadastro_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_fornecedorActionPerformed
        newCadastro(btn_cadastro_fornecedor, RegisterFornecedor.class, "Novo Fornecedor");
    }//GEN-LAST:event_btn_cadastro_fornecedorActionPerformed

    private void btn_cadastro_produto_fabricadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_produto_fabricadoActionPerformed
        newCadastro(btn_cadastro_produto_fabricado, RegisterProdutoFabricado.class, "Novo Produto Fabricado");
    }//GEN-LAST:event_btn_cadastro_produto_fabricadoActionPerformed

    private void btn_cadastro_tipo_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_tipo_produtoActionPerformed
        newCadastro(btn_cadastro_tipo_produto, RegisterTipoProduto.class, "Novo Tipo Produto");
    }//GEN-LAST:event_btn_cadastro_tipo_produtoActionPerformed

    private void btn_cadastro_osActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_osActionPerformed
        newCadastro(btn_cadastro_os, RegisterOrdemServico.class, "Nova Ordem de Serviço");
    }//GEN-LAST:event_btn_cadastro_osActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastro_cliente;
    private javax.swing.JButton btn_cadastro_fornecedor;
    private javax.swing.JButton btn_cadastro_mecanico;
    private javax.swing.JButton btn_cadastro_oc;
    private javax.swing.JButton btn_cadastro_of;
    private javax.swing.JButton btn_cadastro_os;
    private javax.swing.JButton btn_cadastro_ov;
    private javax.swing.JButton btn_cadastro_produto;
    private javax.swing.JButton btn_cadastro_produto_fabricado;
    private javax.swing.JButton btn_cadastro_tipo_produto;
    private javax.swing.JButton btn_cadastro_vendedor;
    private javax.swing.JPanel pn_cadastro;
    private javax.swing.JScrollPane sp_cadastro;
    private javax.swing.JToolBar toolbar_cadastro;
    // End of variables declaration//GEN-END:variables
}
