package hermes.client.view.toolbar;

import com.hermes.components.HMFrames.HMInternalFrame;
import hermes.client.controll.frame.LoginController;
import hermes.client.view.search.SearchCliente;
import hermes.client.view.search.SearchMecanico;
import hermes.client.view.search.SearchOrdemServico;
import hermes.client.view.search.SearchProduto;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author iury
 */
public class Pesquisa extends HMInternalFrame {

    public void newPesquisa(JButton btn, Class classe, String title) {
        deopaqueButtons();
        pn_pesquisa.removeAll();
        btn.setBackground(new Color(0, 204, 255));
        btn.setOpaque(true);
        Object ob = new Object();
        try {
            ob = classe.newInstance();
        } catch (InstantiationException ex) {
            Logger.getLogger(Novo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Novo.class.getName()).log(Level.SEVERE, null, ex);
        }
        ((JPanel) ob).setVisible(true);
        pn_pesquisa.add((Component) ob);
        updateUI();
        setBackground(new Color(224, 249, 252));
        setTitle(title);
        setFrameIcon(btn.getIcon());
        pn_pesquisa.setSize(((JPanel) ob).getSize().width, this.getSize().height);
        setSize(((JPanel) ob).getSize().width + 140, ((JPanel) ob).getSize().height + 30);
    }

    public void deopaqueButtons() {
        Component[] componentes = toolbar_pesquisa.getComponents();
        String classe;
        for (int contador = 0; contador < componentes.length; contador++) {
            classe = componentes[contador].getClass().getName();
            try {
                if (classe.contains("JButton")) {
                    ((JButton) componentes[contador]).setOpaque(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Não foi possível resetar os botões!");
            }
        }
    }

    public Pesquisa() {
        initComponents();
        sp_pesquisa.setViewportView(toolbar_pesquisa);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar_pesquisa = new javax.swing.JToolBar();
        btn_pesquisa_produto = new javax.swing.JButton();
        btn_pesquisa_os = new javax.swing.JButton();
        btn_pesquisa_ov = new javax.swing.JButton();
        btn_pesquisa_of = new javax.swing.JButton();
        btn_pesquisa_oc = new javax.swing.JButton();
        btn_pesquisa_cliente = new javax.swing.JButton();
        btn_pesquisa_fornecedor = new javax.swing.JButton();
        btn_pesquisa_vendedor = new javax.swing.JButton();
        btn_pesquisa_mecanico = new javax.swing.JButton();
        btn_pesquisa_tipo_produto = new javax.swing.JButton();
        btn_pesquisa_produto_fabric = new javax.swing.JButton();
        pn_pesquisa = new javax.swing.JPanel();
        sp_pesquisa = new javax.swing.JScrollPane();

        toolbar_pesquisa.setBackground(new java.awt.Color(196, 240, 252));
        toolbar_pesquisa.setFloatable(false);
        toolbar_pesquisa.setOrientation(javax.swing.SwingConstants.VERTICAL);
        toolbar_pesquisa.setRollover(true);
        toolbar_pesquisa.setAutoscrolls(true);

        btn_pesquisa_produto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_pesquisa_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hammer_zoom.png"))); // NOI18N
        btn_pesquisa_produto.setText("Produto");
        btn_pesquisa_produto.setFocusable(false);
        btn_pesquisa_produto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_produto.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_produto.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_produto.setOpaque(false);
        btn_pesquisa_produto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pesquisa_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_produtoActionPerformed(evt);
            }
        });
        toolbar_pesquisa.add(btn_pesquisa_produto);

        btn_pesquisa_os.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_pesquisa_os.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard_zoom.png"))); // NOI18N
        btn_pesquisa_os.setText("Ordem Serviço");
        btn_pesquisa_os.setFocusable(false);
        btn_pesquisa_os.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_os.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_os.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_os.setOpaque(false);
        btn_pesquisa_os.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pesquisa_os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_osActionPerformed(evt);
            }
        });
        toolbar_pesquisa.add(btn_pesquisa_os);

        btn_pesquisa_ov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_pesquisa_ov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/certificate_zoom.png"))); // NOI18N
        btn_pesquisa_ov.setText("Ordem Venda");
        btn_pesquisa_ov.setFocusable(false);
        btn_pesquisa_ov.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_ov.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_ov.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_ov.setOpaque(false);
        btn_pesquisa_ov.setPreferredSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_ov.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar_pesquisa.add(btn_pesquisa_ov);

        btn_pesquisa_of.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_pesquisa_of.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_zoom.png"))); // NOI18N
        btn_pesquisa_of.setText("Ordem Fabric.");
        btn_pesquisa_of.setFocusable(false);
        btn_pesquisa_of.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_of.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_of.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_of.setOpaque(false);
        btn_pesquisa_of.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar_pesquisa.add(btn_pesquisa_of);

        btn_pesquisa_oc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping_basket_zoom.png"))); // NOI18N
        btn_pesquisa_oc.setText("Ordem Compra");
        btn_pesquisa_oc.setFocusable(false);
        btn_pesquisa_oc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_oc.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_oc.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_oc.setOpaque(false);
        btn_pesquisa_oc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar_pesquisa.add(btn_pesquisa_oc);

        btn_pesquisa_cliente.setBackground(new java.awt.Color(0, 204, 255));
        btn_pesquisa_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_pesquisa_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_zoom.png"))); // NOI18N
        btn_pesquisa_cliente.setText("Cliente");
        btn_pesquisa_cliente.setFocusable(false);
        btn_pesquisa_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_cliente.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_cliente.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_cliente.setOpaque(false);
        btn_pesquisa_cliente.setPreferredSize(new java.awt.Dimension(80, 85));
        btn_pesquisa_cliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pesquisa_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_clienteActionPerformed(evt);
            }
        });
        toolbar_pesquisa.add(btn_pesquisa_cliente);

        btn_pesquisa_fornecedor.setBackground(new java.awt.Color(196, 240, 252));
        btn_pesquisa_fornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_pesquisa_fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/management_zoom.png"))); // NOI18N
        btn_pesquisa_fornecedor.setText("Fornecedor");
        btn_pesquisa_fornecedor.setFocusable(false);
        btn_pesquisa_fornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_fornecedor.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_fornecedor.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_fornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pesquisa_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_fornecedorActionPerformed(evt);
            }
        });
        toolbar_pesquisa.add(btn_pesquisa_fornecedor);

        btn_pesquisa_vendedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_pesquisa_vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_zoom.png"))); // NOI18N
        btn_pesquisa_vendedor.setText("Vendedor");
        btn_pesquisa_vendedor.setFocusable(false);
        btn_pesquisa_vendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_vendedor.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_vendedor.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_vendedor.setOpaque(false);
        btn_pesquisa_vendedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pesquisa_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_vendedorActionPerformed(evt);
            }
        });
        toolbar_pesquisa.add(btn_pesquisa_vendedor);

        btn_pesquisa_mecanico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_pesquisa_mecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/technical_wrench_zoom.png"))); // NOI18N
        btn_pesquisa_mecanico.setText("Mecânico");
        btn_pesquisa_mecanico.setFocusable(false);
        btn_pesquisa_mecanico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_mecanico.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_mecanico.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_mecanico.setOpaque(false);
        btn_pesquisa_mecanico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pesquisa_mecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_mecanicoActionPerformed(evt);
            }
        });
        toolbar_pesquisa.add(btn_pesquisa_mecanico);

        btn_pesquisa_tipo_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/location_zoom.png"))); // NOI18N
        btn_pesquisa_tipo_produto.setText("Tipo Produto");
        btn_pesquisa_tipo_produto.setFocusable(false);
        btn_pesquisa_tipo_produto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_tipo_produto.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_tipo_produto.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_tipo_produto.setOpaque(false);
        btn_pesquisa_tipo_produto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pesquisa_tipo_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_tipo_produtoActionPerformed(evt);
            }
        });
        toolbar_pesquisa.add(btn_pesquisa_tipo_produto);

        btn_pesquisa_produto_fabric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/technical_wrench_zoom.png"))); // NOI18N
        btn_pesquisa_produto_fabric.setText("Produto Fabric.");
        btn_pesquisa_produto_fabric.setFocusable(false);
        btn_pesquisa_produto_fabric.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pesquisa_produto_fabric.setMaximumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_produto_fabric.setMinimumSize(new java.awt.Dimension(89, 89));
        btn_pesquisa_produto_fabric.setOpaque(false);
        btn_pesquisa_produto_fabric.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pesquisa_produto_fabric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa_produto_fabricActionPerformed(evt);
            }
        });
        toolbar_pesquisa.add(btn_pesquisa_produto_fabric);

        setBackground(new java.awt.Color(224, 249, 252));
        setTitle("Pesquisa");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N

        pn_pesquisa.setOpaque(false);

        javax.swing.GroupLayout pn_pesquisaLayout = new javax.swing.GroupLayout(pn_pesquisa);
        pn_pesquisa.setLayout(pn_pesquisaLayout);
        pn_pesquisaLayout.setHorizontalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        pn_pesquisaLayout.setVerticalGroup(
            pn_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        sp_pesquisa.setBackground(new java.awt.Color(102, 153, 255));
        sp_pesquisa.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sp_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addComponent(pn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisa_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_produtoActionPerformed
        newPesquisa(btn_pesquisa_produto, SearchProduto.class, "Pesquisa Produto");
    }//GEN-LAST:event_btn_pesquisa_produtoActionPerformed

    private void btn_pesquisa_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_clienteActionPerformed
        newPesquisa(btn_pesquisa_cliente, SearchCliente.class, "Pesquisa Cliente");
    }//GEN-LAST:event_btn_pesquisa_clienteActionPerformed

    private void btn_pesquisa_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_fornecedorActionPerformed
        //newPesquisa(btn_pesquisa_fornecedor, CadastroFornecedor.class, "Novo Fornecedor");
    }//GEN-LAST:event_btn_pesquisa_fornecedorActionPerformed

    private void btn_pesquisa_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_vendedorActionPerformed
        //newPesquisa(btn_pesquisa_vendedor, CadastroVendedor.class, "Novo Vendedor");
    }//GEN-LAST:event_btn_pesquisa_vendedorActionPerformed

    private void btn_pesquisa_mecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_mecanicoActionPerformed
        newPesquisa(btn_pesquisa_mecanico, SearchMecanico.class, "Pesquisa Mecânico");
    }//GEN-LAST:event_btn_pesquisa_mecanicoActionPerformed

    private void btn_pesquisa_tipo_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_tipo_produtoActionPerformed
        //newPesquisa(btn_pesquisa_tipo_produto, CadastroTipoProduto.class, "Novo Tipo Produto");
    }//GEN-LAST:event_btn_pesquisa_tipo_produtoActionPerformed

    private void btn_pesquisa_produto_fabricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_produto_fabricActionPerformed
        //newPesquisa(btn_pesquisa_produto_fabric, CadastroProdutoFabricado.class, "Novo Produto Fabricado");
    }//GEN-LAST:event_btn_pesquisa_produto_fabricActionPerformed

    private void btn_pesquisa_osActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa_osActionPerformed
        newPesquisa(btn_pesquisa_os, SearchOrdemServico.class, "Pesquisa Ordem de Serviço");
    }//GEN-LAST:event_btn_pesquisa_osActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pesquisa_cliente;
    private javax.swing.JButton btn_pesquisa_fornecedor;
    private javax.swing.JButton btn_pesquisa_mecanico;
    private javax.swing.JButton btn_pesquisa_oc;
    private javax.swing.JButton btn_pesquisa_of;
    private javax.swing.JButton btn_pesquisa_os;
    private javax.swing.JButton btn_pesquisa_ov;
    private javax.swing.JButton btn_pesquisa_produto;
    private javax.swing.JButton btn_pesquisa_produto_fabric;
    private javax.swing.JButton btn_pesquisa_tipo_produto;
    private javax.swing.JButton btn_pesquisa_vendedor;
    private javax.swing.JPanel pn_pesquisa;
    private javax.swing.JScrollPane sp_pesquisa;
    private javax.swing.JToolBar toolbar_pesquisa;
    // End of variables declaration//GEN-END:variables
}
